### ISSUE TITLE
won't compile on Mac OSX10.9 with Xcode 5.1.1

### ISSUE THREAD

**Issue by tessus** [ElDeveloper/macfusion2#11]
The code doesn't compile on Mac OSX10.9 with Xcode 5.1.1.

It won't compile, because GC is no longer supported and converting to ARC doesn't work either.

**Comment by tessus** [comment]
it seems that @stewiem2000 did some changes to the code last year. I haven't had time to check for ARC changes, but he fixed some bugs like **Fix misuse of logical-OR** https://github.com/stewiem2000/macfusion2/commit/8351bd263c89f61bed4faf2ab25f59d58ee2f7c6

**Comment by tessus** [comment]
@ElDeveloper - I think your task got a lot easier. :-) @stewiem2000's code is forked from https://github.com/166MMX/macfusion2 which actually has ARC changes. maybe you can pull them...

**Comment by ElDeveloper** [comment]
Whoaaa!! Awesome find @tessus. Have you had a chance to test it out?

**Comment by tessus** [comment]
Unfortunately I haven't had time yet.

**Comment by alexwhittemore** [comment]
Man, look at @166MMX go!

**Comment by tessus** [comment]
I've merged @166MMX's changes into your current master. The merge conflicts were quite extensive and I spent only a couple of hours to resolve them. Thus I can't be sure, if everything works as expected.

I was able to compile and run it though (on 10.11.6 with Xcode 7.3.1).

https://github.com/tessus/macfusion2/tree/166MMX

There are still other things to change like Interface Builder settings for a few .xib files and other minor adjustments, but these things can be done after the merge has been tested and deemed valid. I also suggest merging some, if not all commits done by @stewiem2000 which are here https://github.com/stewiem2000/macfusion2/commits/master

**Comment by alexwhittemore** [comment]
Fantastic work!

**Comment by tessus** [comment]
Thanks, but @ElDeveloper has to verify that the merge didn't screw up any of his earlier commits. Unfortunately the other repos were forked from the original. To that end, what are the next steps @ElDeveloper?
What do you think of @stewiem2000's changes? Most of them look like cleanup and bug fixing.
Shall I try to merge them as well?

**Comment by ElDeveloper** [comment]
First of all, thanks for taking the initiative, this is awesome!
Secondly, the changes that I have made have all mostly been rather
minor, nothing that disrupts the code-base too much. As for integrating
more bug fixes and cleanup, I think that would be a good idea! I will
pull your changes tonight and test locally! This is very exciting!!!

**Comment by tessus** [comment]
I'll work on cherry-picking  commits from @stewiem2000's fork and put them in a separate branch.

Another thing I was wondering about: don't you want to change the Sparkle update feed to your server?

**Comment by ElDeveloper** [comment]
@tessus, it's alive! It compiles in 10.11.6, however it seems like there's a problem with the agent, can't be started, or something along those lines. I will try to have a look, unless someone beats me to it.

By glancing through the warnings, it seems that most of them are straightforward, which is great!

> Another thing I was wondering about: don't you want to change the Sparkle update feed to your server?

This would be a good thing to do for sure. However I don't have a server of my own that I can reliably use for this 😞. This is something we'll have to figure out at some point, would be great to have Sparkle just work again.

Thanks again for the hard work!!! I'll debug further later in the week.

**Comment by tessus** [comment]
Yes, I noticed that. I think you might not have pulled the latest commit 686c571a7c003b36627adb7c3cddce7b558460f3

These 2 settings have to be set in the project: CLANG_ENABLE_OBJC_ARC = YES, CLANG_LINK_OBJC_RUNTIME = YES

Btw, I've cherry-picked and merged @stewiem2000's cleanup commits and they are in a new branch (on top of the previous one): https://github.com/tessus/macfusion2/tree/stewiem2000-cherry-picks

Other than that it would be great, if you could look at @stewiem2000's other changes. They look promising and could be a good addition:

```
* 368293f | 2015-06-24 15:19:25 +0100 |  (stewiem2000/master) - Add a document and script mentioning how to rebuild SSHFS
* afdb59c | 2015-06-24 15:14:15 +0100 |  - Remove forced-TTY requirement; this is better handled with a sudoers config change
* a3b63aa | 2015-06-24 15:12:39 +0100 |  - Add the ability to forward the ssh-agent connection; this has necessitated bundling a non-static version of sshfs with associated libraries
* d0931d0 | 2015-06-22 16:40:21 +0100 |  - Facilitate using sudo with the remote end of SSHFS
*   d837632 | 2015-01-31 22:22:39 +0000 |  Merge branch 'my-additions'
|\
| * 652be34 | 2015-01-31 13:53:31 +0000 |  (stewiem2000/my-additions) - Use correct format string for dict key from https://github.com/ifraimow/macfusion2/commit/3aa843d2e047e94c213cc5fb807fd5c1a6964ff5
| * 13fbc60 | 2015-01-31 13:45:30 +0000 |  - Add the ability to specify the umask
| * 63233c5 | 2015-01-31 12:07:03 +0000 |  - Add number formatters to restrict port, UID and GID values
| * 2dee068 | 2015-01-31 12:06:40 +0000 |  - Default the UID/GID values to those of the current user
| * b413cf5 | 2015-01-31 12:06:23 +0000 |  - Disable the UID/GID inputs if "Map User" is not selected
| * e911eb8 | 2015-01-31 12:06:04 +0000 |  - Add support for additional SSHFS configuration
```

As a side note, I've noticed that the IconFamily code is mostly deprecated. Maybe you can find a newer, more recent version, or a substitute. On my MacBook the icons look rather off:

<img width="499" alt="screen shot 2016-08-16 at 01 13 39" src="https://cloud.githubusercontent.com/assets/223439/17688610/cdb7593c-634e-11e6-89db-5ea5de9e740e.png">

**Comment by jcrbloch** [comment]
I downloaded the ElDeveloper/macfusion2 branch and built it on MacOS Sierra with Xcode8. The build went through without problem, but when starting MacFusion it aborts because the Agent can not be started, even though it was properly built. Any idea?

**Comment by jcrbloch** [comment]
The same problem occurs with the https://github.com/tessus/macfusion2/tree/stewiem2000-cherry-picks branch. Built on Sierra with Xcode8 works fine using "xcodebuild -sdk macosx10.12 -target All", 
but starting Macfusion fails with the message "Could not start or connect to the macfusion agent".

**Comment by jcrbloch** [comment]
I got one step further now. I put aside the Macfusion directory in ~/Library/Application Support and started afresh. Now the macfusionAgent starts, and so does macfusion. The new problem is that I am not able to mount any sshfs server, as I constantly get the message: "Could not mount filesystem: Mount path could not be created."

**Comment by jcrbloch** [comment]
Somehow Macfusion can no longer access /Volumes to create the mountpoint, so I got it to work by adding a Mount Point and Volume Name in the Macfusion options of each added filesystem. As mount point I choose an UNEXISTANT folder name in my home folder (e.g. /Users/<me>/Volumes) and as volume name the name I gave to the filesystem (otherwise it will use the host name). Now everything seems to be fine and the file system shows up Finder, etc.

**Comment by jcrbloch** [comment]
But this is unfortunately not the end of the story. If Macfusion together with the Macfusionagent are stopped, it will not start again until the Macfusion folder in "Application Support" has been again removed, which means that all stored FileSystems are gone. I have not yet found a way around this, as making a copy of the configurations and restoring the configuration file after starting the agent is of no use because the configurations are read by the agent when it is started. More help needed.

**Comment by ElDeveloper** [comment]
@tessus I will try that, thanks!

@jcrbloch thanks for the in-depth debugging, I don't have a Sierra system, but I'll try in my El Capitan  installation. The problem with the Application Support folders may be due to an API change on the plist files, this is a very helpful guide going in, cheers 👍

**Comment by tessus** [comment]
I've had some time to test it as well and I experienced similar issues as @jcrbloch although I was able to mount via sshfs (from my previous post you can see that I am on 10.11.6).

In the beginning I did not have issues with it, because I haven't had any mount points added. But even after adding some mount points I was able to start it again and see them in the main window. 

At some point (**and I have no clue why**) it stopped working and I had to remove the _macfusion_ folder in the _Application Support_ directory. I'm really puzzled by this, because it makes no sense. At least not to me.

**Comment by jcrbloch** [comment]
Situation here is unchanged: when I reboot my machine the Macfufsion Agent will not start until I remove the Macfusion folder in Application Support. This means that I have to reenter my external Filesystems in Macfusion at every reboot... not very practical ;)

**Comment by jcrbloch** [comment]
If I look at the log console I see that when starting the Agent I get zillions of lines with:
macfusionAgent	Loading fs at /Users/bloch/Library/Application Support/Macfusion/Filesystems/35298D39-CEEB-4A83-9F71-47E8EE4C50A8.macfusion

and then finally:
macfusionAgent	*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x60000028fff0 of class SSHServerFS was deallocated while key value observers were still registered with it.

**Comment by jcrbloch** [comment]
In fact the only culprits prohibiting the Agent to start are the following commands in the filesystem descriptions:
	<key>type</key>
	<string>org.mgorbach.macfusion2.sshfs</string>
Obviously this is a crucial key, but nevertheless when commenting this out the Agent starts, but without showing any filesystems.

**Comment by jcrbloch** [comment]
Note that this is not an sshfs problem per se on Sierra, as the command line sshfs works properly fine if one installs FUSE 3.4 or higher.

**Comment by tessus** [comment]
@ElDeveloper have you had success fixing the `Application Support` API issues?

**Comment by ElDeveloper** [comment]
Looking at it just now 👀

**Comment by ElDeveloper** [comment]
Not having much success right now, what I've been able to gather (at least from the exception below) is that there's some observers that are not being removed, and this is causing that exception to be raised.

```
9/3/16 6:56:29.845 AM macfusionAgent[60640]: *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x6100000945a0 of class SSHServerFS was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x610000256650> (
<NSKeyValueObservance 0x6100000d3e80: Observer: 0x6100000945a0, Key path: statusInfo, Options: <New: YES, Old: YES, Prior: NO> Context: 0x0, Property: 0x6180000410e0>
<NSKeyValueObservance 0x6100000d3d30: Observer: 0x6100000945a0, Key path: parameters, Options: <New: YES, Old: YES, Prior: NO> Context: 0x0, Property: 0x618000041320>
<NSKeyValueObservance 0x6100000d3ef0: Observer: 0x6100000945a0, Key path: status, Options: <New: YES, Old: YES, Prior: NO> Context: 0x0, Property: 0x618000041140>
<NSKeyValueObservance 0x6100000d3f60: Observer: 0x600000a61a80, Key path: status, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x618000041140>
)'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff960e84f2 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff9fda573c objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff9614f4bd +[NSException raise:format:] + 205
	3   Foundation                          0x00007fff93edef80 NSKVODeallocate + 294
	4   CoreFoundation                      0x00007fff9602188d -[__NSDictionaryM dealloc] + 269
	5   libobjc.A.dylib                     0x00007fff9fda1c42 _ZL27object_cxxDestructFromClassP11objc_objectP10objc_class + 127
	6   libobjc.A.dylib                     0x00007fff9fd9bdab objc_destructInstance + 116
	7   libobjc.A.dylib                     0x00007fff9fd9bd0d object_dispose + 22
	8   Foundation                          0x00007fff93f42620 -[NSKeyValueMutableArray _proxyNonGCFinalize] + 59
	9   Foundation                          0x00007fff93f7cc2c -[NSKeyValueSlowMutableArray _proxyNonGCFinalize] + 94
	10  Foundation                          0x00007fff93ef2f83 _NSKeyValueProxyDeallocate + 254
	11  Foundation                          0x00007fff93f42560 -[NSKeyValueMutableArray dealloc] + 17
	12  libobjc.A.dylib                     0x00007fff9fd9aac4 _ZN12_GLOBAL__N_119AutoreleasePoolPage3popEPv + 476
	13  CoreFoundation                      0x00007fff9601bc12 _CFAutoreleasePoolPop + 50
	14  Foundation                          0x00007fff93e7a9ea -[NSAutoreleasePool drain] + 153
	15  AppKit                              0x00007fff91028ee2 -[NSApplication run] + 1036
	16  macfusionAgent                      0x0000000100001b2a main + 170
	17  macfusionAgent                      0x0000000100001a74 start + 52
)
```

I've tried is adding some calls to `removeObserver`, however this doesn't seem to be sufficient, the problem prevails however this time with fewer objects:

```
9/3/16 8:03:02.094 AM macfusionAgent[64707]: *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x610000280fa0 of class SSHServerFS was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x6000004455e0> (
<NSKeyValueObservance 0x6100000d12c0: Observer: 0x610000670600, Key path: status, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x6180000484f0>
)'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff960e84f2 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff9fda573c objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff9614f4bd +[NSException raise:format:] + 205
	3   Foundation                          0x00007fff93edef80 NSKVODeallocate + 294
	4   CoreFoundation                      0x00007fff9602188d -[__NSDictionaryM dealloc] + 269
	5   libobjc.A.dylib                     0x00007fff9fda1c42 _ZL27object_cxxDestructFromClassP11objc_objectP10objc_class + 127
	6   libobjc.A.dylib                     0x00007fff9fd9bdab objc_destructInstance + 116
	7   libobjc.A.dylib                     0x00007fff9fd9bd0d object_dispose + 22
	8   Foundation                          0x00007fff93f42620 -[NSKeyValueMutableArray _proxyNonGCFinalize] + 59
	9   Foundation                          0x00007fff93f7cc2c -[NSKeyValueSlowMutableArray _proxyNonGCFinalize] + 94
	10  Foundation                          0x00007fff93ef2f83 _NSKeyValueProxyDeallocate + 254
	11  Foundation                          0x00007fff93f42560 -[NSKeyValueMutableArray dealloc] + 17
	12  libobjc.A.dylib                     0x00007fff9fd9aac4 _ZN12_GLOBAL__N_119AutoreleasePoolPage3popEPv + 476
	13  CoreFoundation                      0x00007fff9601bc12 _CFAutoreleasePoolPop + 50
	14  Foundation                          0x00007fff93e7a9ea -[NSAutoreleasePool drain] + 153
	15  AppKit                              0x00007fff91028ee2 -[NSApplication run] + 1036
	16  macfusionAgent                      0x0000000100001b2a main + 170
	17  macfusionAgent                      0x0000000100001a74 start + 52
)
```

Not sure how this was working before, but I'm also not too familiar with the KVO framework.

-------------------

Just in case my current diff looks like this (not all of these changes may be needed, just focus on the `addObserver` changes):

```patch
diff --git a/MFCore/MFClient.m b/MFCore/MFClient.m
index fa20e93..18c234d 100644
--- a/MFCore/MFClient.m
+++ b/MFCore/MFClient.m
@@ -82,6 +82,14 @@ static MFClient *sharedClient = nil;
 	[nc addObserver:self selector:@selector(handleApplicationTerminatingNotification:) name:NSApplicationWillTerminateNotification object:nil];
 }
 
+- (void)dealloc{
+	NSDistributedNotificationCenter *dnc = [NSDistributedNotificationCenter defaultCenter];
+	[dnc removeObserver:self name:kMFRecentsUpdatedNotification object:kMFDNCObject];
+
+	NSNotificationCenter *nc = [NSNotificationCenter defaultCenter];
+	[nc removeObserver:self name:NSApplicationWillTerminateNotification object:nil];
+}
+
 - (id)init {
 	self = [super init];
 	if (self != nil) {
diff --git a/MFCore/MFCommunicationServer.m b/MFCore/MFCommunicationServer.m
index eeadb1b..6e9c5e8 100644
--- a/MFCore/MFCommunicationServer.m
+++ b/MFCore/MFCommunicationServer.m
@@ -48,6 +48,14 @@ static MFCommunicationServer *sharedServer = nil;
 	[[MFFilesystemController sharedController] addObserver:self forKeyPath:@"recents" options:NSKeyValueObservingOptionNew | NSKeyValueObservingOptionOld context:nil];
 }
 
+- (void)dealloc {
+	NSArray *filesystems = [[self filesystemController] filesystems];
+	NSIndexSet *indexes = [NSIndexSet indexSetWithIndexesInRange:NSMakeRange(0, [filesystems count])];
+
+	[filesystems removeObserver:self fromObjectsAtIndexes:indexes forKeyPath:@"status"];
+	[filesystems removeObserver:self fromObjectsAtIndexes:indexes forKeyPath:@"parameters"];
+}
+
 - (id) init {
 	self = [super init];
 	if (self != nil) {
diff --git a/MFCore/MFMainController.h b/MFCore/MFMainController.h
index 4fe1c26..594dd90 100644
--- a/MFCore/MFMainController.h
+++ b/MFCore/MFMainController.h
@@ -16,7 +16,7 @@
 
 #import <Cocoa/Cocoa.h>
 
-@interface MFMainController : NSObject {	
+@interface MFMainController <NSApplicationDelegate> : NSObject {
 }
 
 + (MFMainController *)sharedController;
diff --git a/MFCore/MFServerFS.m b/MFCore/MFServerFS.m
index 3656df3..c47f9b6 100644
--- a/MFCore/MFServerFS.m
+++ b/MFCore/MFServerFS.m
@@ -164,18 +164,24 @@
 - (void)registerGeneralNotifications {
 	[self addObserver:self 
 		   forKeyPath:KMFStatusDict
-			  options:NSKeyValueObservingOptionOld || NSKeyValueObservingOptionNew
+			  options:NSKeyValueObservingOptionOld | NSKeyValueObservingOptionNew
 			  context:nil];
 	[self addObserver:self
 		   forKeyPath:kMFParameterDict
-			  options:NSKeyValueObservingOptionOld || NSKeyValueObservingOptionNew
+			  options:NSKeyValueObservingOptionOld | NSKeyValueObservingOptionNew
 			  context:nil];
 	[self addObserver:self
 		   forKeyPath:kMFSTStatusKey
-			  options:NSKeyValueObservingOptionOld || NSKeyValueObservingOptionNew
+			  options:NSKeyValueObservingOptionOld | NSKeyValueObservingOptionNew
 			  context:nil];
 }
 
+- (void)dealloc {
+	[self removeObserver:self forKeyPath:KMFStatusDict];
+	[self removeObserver:self forKeyPath:kMFParameterDict];
+	[self removeObserver:self forKeyPath:kMFSTStatusKey];
+}
+
 - (NSMutableDictionary *)initializedStatusInfo {
 	NSMutableDictionary *initialStatusInfo = [NSMutableDictionary dictionaryWithCapacity:5];
 	// Initialize the important keys in the status dictionary
@@ -384,10 +390,10 @@
 - (void)unmount {
 	MFLogS(self, @"Unmounting");
 	NSString* path = [[self mountPath] stringByStandardizingPath];
-	NSString *taskPath = @"/sbin/umount";
+	NSString *taskPath = @"/usr/sbin/diskutil";
 	NSTask* t = [[NSTask alloc] init];
 	[t setLaunchPath:taskPath];
-	[t setArguments:[NSArray arrayWithObject:path]];
+	[t setArguments:[NSArray arrayWithObjects:@"unmount", path, nil]];
 	[t launch];
 	
 	/*
diff --git a/Settings/MFSettingsController.m b/Settings/MFSettingsController.m
index e3181b2..7a5b765 100644
--- a/Settings/MFSettingsController.m
+++ b/Settings/MFSettingsController.m
@@ -580,6 +580,7 @@
 }
 
 - (void)dealloc {
+	[[MFPreferences sharedPreferences] removeObserver:self forKeyPath:kMFPrefsAutosize context:(__bridge void *)(self)];
 	[client setDelegate:nil];
 }
```

**Comment by ElDeveloper** [comment]
HT to this answer on SO: http://stackoverflow.com/a/6960224/379593

**Comment by ElDeveloper** [comment]
I think I figured it out, I've pushed my changes to https://github.com/ElDeveloper/macfusion2/tree/kvo-bug, please pull these down and make sure it works for you. Seems to be working for me 🎉 

I added the commit on top of @tessus' changes at 686c571a7c003b36627adb7c3cddce7b558460f3. I haven't yet merged in and tested all the other changes from the cherry-picked branch. If someone else can confirm that this last patch works, I'll look at the other changes and merge them as appropriate.

**Comment by jcrbloch** [comment]
I pulled the kvo-bug branch and built macfusion on MasOS Sierra. I had to restart the agent a couple of times and reenter one of the filesystems, but since then the program seems to be stable. Thanks Yoshiki.

The remaining problem on Sierra, which is independent of the solved bug, is that I can no longer mount the filesystems in /Volume, as there seems to be a new permission problem. The error message is "Mount path could not be created". The only consistent solution for me right now is to explicitly enter a Mount Point for each filesystem. The Mount Point has to be an inexistent filename, e.g. /Users/<user>/Volumes/<name>.

**Comment by ElDeveloper** [comment]
I see, I don't have a Sierra system to test in, and I'm not up to date
with the latest API changes from Apple, anyone knows anything about
this? When I tested in my system (running El Capitan), Macfusion was
able to mount the filesystem in my /Volumes/ folder without a problem.

**Comment by jcrbloch** [comment]
It may have something to do with what is documented here [http://apple.stackexchange.com/questions/249627/programmatically-creating-mount-points-in-macos-10-12] saying that:
_Apple have confirmed to me (https://openradar.appspot.com/radar?id=4948585099558912) that with macOS 10.12, permissions to create a folder inside /Volumes require root access.

Using the mount command requires that the mount point exists first, so you're going to have to sudo to create that folder for the mount point._

This has not helped me however. Even when creating the directories in /Volumes and changing ownership macfusion still cannot mount them. Maybe I have to change some more permissions.

**Comment by ElDeveloper** [comment]
Thanks!! I think the reason why Macfusion can't mount in the existing
folders, is because it has a check (IIRC) where if the directory already
exists, then it will fail to mount the volume. I think a better
solution, would be to mount all the volumes by default in the home
directory, any votes or alternative solutions?

**Comment by jcrbloch** [comment]
The home directory may lead to clashes with existing files. Would it not be better to mount it in a dedicated subfolder like ~/Volumes ?

**Comment by ElDeveloper** [comment]
Either or, I don't have a strong preference. Thoughts?

**Comment by tessus** [comment]
Yep, macOS will be one more step closer to iOS and thus less usable. It's bad how Apple de-professionalizes its flagship system. Opensource developers won't be able to code for macOS anymore, since Apps will have to be installed through the AppStore which in turn has great limitations.

Anyway, ranting aside, I like @jcrbloch's suggestion `~/Volumes`. You could make it conditional, if you wanted to: `~/Volumes` for systems >= 10.12 and `/Volumes` for <= 10.11. (not really necessary though)

**Comment by ElDeveloper** [comment]
> Anyway, ranting aside, I like @jcrbloch's suggestion `~/Volumes`. You could make it conditional, if you wanted to: `~/Volumes` for systems >= 10.12 and `/Volumes` for <= 10.11. (not really necessary though)

Great point, I'll give this a shot, and add all the other commits to
this branch, hopefully we can have something working soon.

BTW, when I was testing over the weekend, I noticed the icons Macfusion
were sized incorrectly once, and then after a few restarts the icons
were fine. Not sure if anyone's encountered this same problem.

Thanks!

Yoshiki.

**Comment by tessus** [comment]
I'll do some testing tomorrow and let you know. But as I mentioned in an earlier https://github.com/ElDeveloper/macfusion2/issues/11#issuecomment-240003097, the IconFamily code is mostly deprecated. Maybe it is possible to find a newer version or a replacement.

**Comment by kaloprominat** [comment]
fellows? any luck on fixing macfusion for macOS Sierra?

**Comment by jcrbloch** [comment]
@pavel: as I wrote 2 weeks ago the kvo-bug branch described above compiles and works fine on Sierra. Just tell me if you have any trouble getting it to work.

**Comment by Serik0** [comment]
@jcrbloch 
Hello!
Could you please share one more "pre-release" to allow just downloading this version with fixes?

Thanks in advance.

**Comment by wpoulos** [comment]
I can't seem to get the agent started or the built version of kvo-bug MacFusion to launch. Is there something else I need to do? The build seemed to work fine. I am on Sierra.

**Comment by Serik0** [comment]
Hello.
I've built MacFusion  from kvo-bug branch and upload here.
 
[Macfusion-kvo-bug.zip](https://github.com/ElDeveloper/macfusion2/files/489002/Macfusion-kvo-bug.zip)

**Comment by KatsOide** [comment]
I have tested Serik0's version for SSHFS on Sierra. It failed:

default	09:15:03.929920 +0200	macfusionAgent	Mounting
default	09:15:03.948220 +0200	Macfusion	Note status changed for fs <MFClientFS: 0x6000000e8880> (xxx) to Waiting to Mount
default	09:15:04.114916 +0200	Macfusion	Note status changed for fs <MFClientFS: 0x6000000e8880> (xxx) to Failed to Mount

I am using osxfuse 3.5.1.

**Comment by jcrbloch** [comment]
@KatsOide: did you follow my advice which I gave two weeks ago? On Sierra, users no longer have the permission to mount their own filesystems in /Volume. So you have to explicitly create your own  Mount Point for each filesystem. The Mount Point has to be an inexistent filename, e.g. /Users/Volumes/<filesystem>.

**Comment by KatsOide** [comment]
@ElDeveloper/macfusion2 
Yes, I did follow your advice on the permission of /Volumes. Thus I set it writable to everybody. Then it works for other mounter such as ExpanDrive, etc. I think it is not the issue in my case.

**Comment by KatsOide** [comment]
In my case, the issue was not in MacFusion, but in sshfs/osxfuse: https://github.com/osxfuse/osxfuse/issues/315

**Comment by jcrbloch** [comment]
Did you install the latest osxfuse beta version?

**Comment by KatsOide** [comment]
Yes, I installed osxfuse 3.5.1 and sshfs 2.5.0, which are the latests.

**Comment by KatsOide** [comment]
@jcrbloch
After reinstalling osxfuse 3.4.3, 3.4.0, 3.5.0, 3.5.1 and restarted mac several times, my problem has gone. Now MacFusion of your version works perfectly on Sierra. Thank you very much.

**Comment by ElDeveloper** [comment]
I appreciate everyone's patience, I believe I should have some time over
the weekend to upload a new pre-release that includes the patches that
have been discussed in this thread so far. Thanks everyone!

**Comment by ElDeveloper** [comment]
If someone can start testing, that would be wonderful: https://github.com/ElDeveloper/macfusion2/releases/tag/2.1.1-dev

**Comment by tessus** [comment]
Aweseome job @ElDeveloper. But there are still a few items I'd like to bring up. This thread got some attention now, so I'll elaborate here, but we can create separate issues for all of the items below:
- my other [branch](https://github.com/tessus/macfusion2/tree/stewiem2000-cherry-picks) (which I merged from @stewiem2000's code) includes a lot of fixes that might be valuable to this project
- the IconFamily code hast to be reworked or replaced due to deprecated API calls
- Sparkle feed changes (I can provide space on my server to host updates and the feed)
- macfuse -> osxfuse migration, link the correct framework

How do you want to handle further development? Maybe we can figure it out via email, since most people might not be interested in the details. You can find my email in my profile.

Please let me know what you think.

**Comment by gaelfoppolo** [comment]
@ElDeveloper, crash on launch, here the report: http://pastebin.com/T7nJCEPj

**Comment by artua** [comment]
Crash while trying to launch agent.
$ sshfs --version
SSHFS version 2.5 (OSXFUSE SSHFS 2.5.0)
OSXFUSE 3.5.2
FUSE library version: 2.9.7

[macfusionAgent_2016-10-03-230752_Artuas-iMac.crash.txt](https://github.com/ElDeveloper/macfusion2/files/507135/macfusionAgent_2016-10-03-230752_Artuas-iMac.crash.txt)

**Comment by ElDeveloper** [comment]
@tessus:
                                                                                
> - my other branch (which I merged from @stewiem2000's code) includes a lot of fixes that might be valuable to this project
                                                                                
I believe those should all be merged in the https://github.com/eldeveloper/macfusion2/tree/sierra branch, I should have mentioned that before.                                                                 
                                                                                
> - the IconFamily code has to be reworked or replaced due to deprecated API calls
                                                                                
Yes agree, however if we can get away without touching this (for now), that would be good (I think).                                                   
                                                                                
> - Sparkle feed changes (I can provide space on my server to host updates and the feed)
                                                                                
This would be wonderful! Would truly bring back life to the project!            
                                                                                
> - macfuse -> osxfuse migration, link the correct framework                    
                                                                                
AFAIK none of the source in macfusion is actually making direct calls to the fuse framework, it all happens through sshfs and ftpfs. But I could be wrong, in any case yes we should only recommend osxfuse as macfuse is deprecated.   

> How do you want to handle further development? Maybe we can figure it out via email, since most people might not be interested in the details. You can find my email in my profile.

✉️  sent!

-----

@gaelfoppolo & @artua, thanks for testing (I'll have a look at the crash reports as soon as I can), I haven't had a chance to update my system (still running El Capitan 🚢). Perhaps compiling in the new OS will do the trick, I'll report back when I do this, unless someone beats me to it.

**Comment by tessus** [comment]
With **sshfs** there are a few issues I'm not 100% sure where I should start.`sshfs_static` is a binary that lives in the project. It is not generated during the build, but when you look at the binary, it is not truly static:

```
./SSHFS/sshfs-static:
	/System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 136.0.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 677.15.0)
	/usr/local/lib/libfuse.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 111.0.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 32.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 476.10.0)
```

The problem here is this part `/usr/local/lib/libfuse.0.dylib`. The compat layer will be removed from osxfuse in the future and thus we need it to be linked against `libosxfuse` instead.

Where does this binary come from?

One of @stewiem2000's commits, namely a3b63aa, which I haven't added to the  https://github.com/tessus/macfusion2/tree/stewiem2000-cherry-picks branch, solves this problem by bundling a non-static version of sshfs with associated libraries.

In any case, I think we have to look into sshfs and how we bundle it in more detail.

As for **IconFamily**, I agree, for now we can leave the IconFamily code as is, but it would be great to get rid of it in the future.

**Comment by 166MMX** [comment]
Hi. Sorry that i just followed the conversations so far. I am glad to see my work has been not only for me but that I could give something back to all of you.

--

Regarding the MacfusionAgent crash report of @artua : This issue is caused by an event loop that is rooted by attaching event listeners:

- [MFFilesystemController  + (MFFilesystemController *)sharedController](https://github.com/ElDeveloper/macfusion2/blob/75989bb517bb945b9a9272e0e9c382ee08576aac/MFCore/MFFilesystemController.m#L53)
- [MFFilesystemController - (id) init](https://github.com/ElDeveloper/macfusion2/blob/75989bb517bb945b9a9272e0e9c382ee08576aac/MFCore/MFFilesystemController.m#L71)
- [MFFilesystemController - (void)setUpVolumeMonitoring](https://github.com/ElDeveloper/macfusion2/blob/75989bb517bb945b9a9272e0e9c382ee08576aac/MFCore/MFFilesystemController.m#L271)  
- [MFFilesystemController  static void diskMounted(DADiskRef disk, void *mySelf)](https://github.com/ElDeveloper/macfusion2/blob/75989bb517bb945b9a9272e0e9c382ee08576aac/MFCore/MFFilesystemController.m#L242)
- [MFFilesystemController  + (MFFilesystemController *)sharedController](https://github.com/ElDeveloper/macfusion2/blob/75989bb517bb945b9a9272e0e9c382ee08576aac/MFCore/MFFilesystemController.m#L53)

The way I fixed it for now was by moving
```objective-c
		[self loadFilesystems];
		[self loadRecentFilesystems];
		[self setUpVolumeMonitoring];
```
[MFFilesystemController - (id) init block](https://github.com/ElDeveloper/macfusion2/blob/75989bb517bb945b9a9272e0e9c382ee08576aac/MFCore/MFFilesystemController.m#L69) to [MFMainController - (void)initialize](https://github.com/ElDeveloper/macfusion2/blob/75989bb517bb945b9a9272e0e9c382ee08576aac/MFCore/MFMainController.m#L51)

--

Regarding the crash of @gaelfoppolo :

I am quite certain that this is a deallocation issue. not quite sure where to start searching but these stack frames should be a good point where to start searching

```
4   org.mgorbach.macfusion2.MFCore	0x000000010a3506b6 mfcGetStateOfLoginItemWithPath + 555
5   org.mgorbach.macfusion2.MFCore	0x000000010a35070a mfcGetStateForAgentLoginItem + 31
6   org.mgorbach.macfusion2       	0x000000010a324580 -[MFSettingsController setup] + 1536
```

- [MFCore BOOL mfcGetStateOfLoginItemWithPath(NSString *path)](https://github.com/ElDeveloper/macfusion2/blob/75989bb517bb945b9a9272e0e9c382ee08576aac/MFCore/MFCore.m#L72)
- [MFCore BOOL mfcGetStateForAgentLoginItem()](https://github.com/ElDeveloper/macfusion2/blob/75989bb517bb945b9a9272e0e9c382ee08576aac/MFCore/MFCore.m#L92) 
- [MFSettingsController - (BOOL)setup](https://github.com/ElDeveloper/macfusion2/blob/75989bb517bb945b9a9272e0e9c382ee08576aac/Settings/MFSettingsController.m#L97)

--

Regarding the sshfs-static mentioned by @tessus 

> Where does this binary come from?

I don't fully remember where it came from. I once [tracked it down](https://github.com/ElDeveloper/macfusion2/commits/75989bb517bb945b9a9272e0e9c382ee08576aac/SSHFS/sshfs-static). If I remember correctly I used sha256 sums to identify the correct origin and version that was committed into this repository. Though I am quite certain that it came from [https://github.com/osxfuse/sshfs](https://github.com/osxfuse/sshfs/tree/03381402b2bb74731388271aa892d94afd0b01e2). I personally am using the Homebrew version of sshfs with a [patch](https://gist.github.com/166MMX/9766101#file-sshfs-c-diff) that enables me to mimic a remote umask for newly created files. The patch though is outdated and wont work with the recent version of [https://github.com/libfuse/sshfs](https://github.com/libfuse/sshfs/blob/e5acfce8eda218d34fa5ded13571f904efa70727/sshfs.c) 

> Sparkle feed changes (I can provide space on my server to host updates and the feed)

I would suggest to use github pages to host the updates feed since it has a widely accepted https certificated.

--

Hope this helps for now.

**Comment by tessus** [comment]
@ElDeveloper ah, yes. I can see that you've merged my other branch into the sierra branch.

But there are still a few commits left from @stewiem2000's code that you might want to consider. They look really interesting and could be a nice addition. But since this is your project you have to decide.

Please note that if you just look at the commits on @stewiem2000's github repo, you won't see all of these commits at the top. I've pasted them here for convenience:

```
* 368293f | 2015-06-24 15:19:25 +0100 |  (stewiem2000/master) - Add a document and script mentioning how to rebuild SSHFS
* afdb59c | 2015-06-24 15:14:15 +0100 |  - Remove forced-TTY requirement; this is better handled with a sudoers config change
* a3b63aa | 2015-06-24 15:12:39 +0100 |  - Add the ability to forward the ssh-agent connection; this has necessitated bundling a non-static version of sshfs with associated libraries
* d0931d0 | 2015-06-22 16:40:21 +0100 |  - Facilitate using sudo with the remote end of SSHFS
*   d837632 | 2015-01-31 22:22:39 +0000 |  Merge branch 'my-additions'
|\
| * 652be34 | 2015-01-31 13:53:31 +0000 |  (stewiem2000/my-additions) - Use correct format string for dict key from https://github.com/ifraimow/macfusion2/commit/3aa843d2e047e94c213cc5fb807fd5c1a6964ff5
| * 13fbc60 | 2015-01-31 13:45:30 +0000 |  - Add the ability to specify the umask
| * 63233c5 | 2015-01-31 12:07:03 +0000 |  - Add number formatters to restrict port, UID and GID values
| * 2dee068 | 2015-01-31 12:06:40 +0000 |  - Default the UID/GID values to those of the current user
| * b413cf5 | 2015-01-31 12:06:23 +0000 |  - Disable the UID/GID inputs if "Map User" is not selected
| * e911eb8 | 2015-01-31 12:06:04 +0000 |  - Add support for additional SSHFS configuration
```

Also I'm wondering, if we should start a new issue (e.g. **next version development**), since this issue (won't compile on 10.9) has already been resolved.

**Comment by ElDeveloper** [comment]
@stewiem2000, thanks for having a look! If you have the patch, would you mind submitting a PR?

@tessus, you are totally right, I am closing this issue as the original problem has been addressed, i.e. Macfusion now supports ARC so it should compile and not crash (in principle). There's many more subtasks, to handle, I've opened a series of issues to do this.

-------------

For the time being, I am having no trouble at running the version that I just uploaded to the pre-releases, can someone else test this?

https://github.com/ElDeveloper/macfusion2/releases/tag/2.1.1-dev

This one has been compiled with Sierra, so hopefully that will solve the problems @gaelfoppolo & @artua  saw. But if not, let's continue the discussion.

----------

Thanks everyone, I'm excited to see this project gain some traction.

**Comment by gaelfoppolo** [comment]
@ElDeveloper 2.1.1-dev still crash at launch for me :/  ([report.txt](https://github.com/ElDeveloper/macfusion2/files/517571/report.txt))

**Comment by Bathtor** [comment]
Same issue as @gaelfoppolo for me. The report looks pretty much the same.

**Comment by keouchao** [comment]
It works for me. I just updated to Sierra ver 10.12, Macbook air 13; download and start 2.1.1-dev without problem. Thanks for the effort.

**Comment by ExtRemo75** [comment]
Same for me, 2.1.1-dev crashes at launch

[report.txt](https://github.com/ElDeveloper/macfusion2/files/519491/report.txt)
 on Sierra 10.12

**Comment by mickey9801** [comment]
I have tried 2.1.1-dev. I launched normally but when I try to mount a remote drive, it turn an error message "Could not mount filesystem: Mount process has terminated unexpectedly"

I have add the key file to ssh-agent and set Mount Point to non-exists folder "/Users/<myname>/Volumes", and tried to assign a Volume Name or leave it blank (Default), both got fail.

**Comment by tessus** [comment]
@mickey9801 Please try to do the following:

```
mkdir $HOME/Volumes
```

Then use `~/Volumes` as the mount point. If the problem still persists, please open a new issue.

**Comment by siliceo** [comment]
@ElDeveloper, for what is worth. I just migrated to a MacBook Pro 2016 [running OSX 10.12.2 (16C67)] and Macfusion 2.0.5-dev is working as expected
