### ISSUE TITLE
Command Line Usage?

### ISSUE THREAD

**Issue by zlanich** [ElDeveloper/macfusion2#15]
Hey there, is it possible to mount an FTP volume via the mac command line/terminal? I've been going insane trying to find a way to do this considering Mac's read-only mount_ftp utility, so I installed MF2 and got the GUI working, but would like to see if I can trigger the mount/unmount via my bash script. Thanks!

**Comment by ElDeveloper** [comment]
Yes, there's a way, but the current implementation is broken (see [mctl](https://github.com/ElDeveloper/macfusion2/blob/master/MFCore/mfctl.m)). That seems to be one of the features that got lost a while ago (way before I started using Macfusion2). 

IIRC, to fix this, we need to find the appropriate way to link the CLI to the library files, and then it should just work.

**Comment by nickcoutsos** [comment]
Is it just about linking the library? Maybe I'm going about it completely wrong, but here's what I've tried knowing little about OSX native development

Attempting to run mfctl:
```
$ /Applications/Macfusion.app/Contents/Resources/mfctl
dyld: Library not loaded: @rpath/MFCore.framework/Versions/A/MFCore
  Referenced from: /Applications/Macfusion.app/Contents/Resources/mfctl.old
  Reason: image not found
Trace/BPT trap: 5
```

Attempting to fix the... I don't know, "missing" rpath?
```
$ install_name_tool  -add_rpath /Applications/Macfusion.app/Contents/Frameworks /Applications/Macfusion.app/Contents/Resources/mfctl
```

Running again
```
$ /Applications/Macfusion.app/Contents/Resources/mfctl
No arguments given. Exiting!
```

So that much is cool. The problem I'm having is that after running this (or any mfctl command) the macfusionAgent crashes with:

```
2016-09-06 22:18:29.933 macfusionAgent[19921:669261] An uncaught exception was raised
2016-09-06 22:18:29.933 macfusionAgent[19921:669261] connection is invalid
2016-09-06 22:18:29.933 macfusionAgent[19921:669261] (
       	0   CoreFoundation                      0x00007fff85a914f2 __exceptionPreprocess + 178
       	1   libobjc.A.dylib                     0x00007fff8cd5873c objc_exception_throw + 48
       	2   CoreFoundation                      0x00007fff85af84bd +[NSException raise:format:] + 205
       	3   Foundation                          0x00007fff94ca0680 -[NSConnection sendInvocation:internal:] + 239
       	4   Foundation                          0x00007fff94c9ff04 -[NSDistantObject methodSignatureForSelector:] + 538
       	5   CoreFoundation                      0x00007fff85a012b8 ___forwarding___ + 312
       	6   CoreFoundation                      0x00007fff85a010f8 _CF_forwarding_prep_0 + 120
       	7   Foundation                          0x00007fff94d52f82 -[NSDistantObject isEqual:] + 68
       	8   CoreFoundation                      0x00007fff85a16fbc -[NSMutableArray removeObject:] + 156
       	9   MFCore                              0x000000010001a99f -[MFCommunicationServer handleConnectionDidDie:] + 259
       	10  CoreFoundation                      0x00007fff85a1cbbc __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
       	11  CoreFoundation                      0x00007fff85a1cb4f ___CFXRegistrationPost_block_invoke + 63
       	12  CoreFoundation                      0x00007fff85a1cac7 _CFXRegistrationPost + 407
       	13  CoreFoundation                      0x00007fff85a1c832 ___CFXNotificationPost_block_invoke + 50
       	14  CoreFoundation                      0x00007fff859d95e2 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1922
       	15  CoreFoundation                      0x00007fff859d8835 _CFXNotificationPost + 693
       	16  Foundation                          0x00007fff94c0a17a -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
       	17  Foundation                          0x00007fff94d3e47f -[NSConnection invalidate] + 879
       	18  CoreFoundation                      0x00007fff85a1cbbc __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
       	19  CoreFoundation                      0x00007fff85a1cb4f ___CFXRegistrationPost_block_invoke + 63
       	20  CoreFoundation                      0x00007fff85a1cac7 _CFXRegistrationPost + 407
       	21  CoreFoundation                      0x00007fff85a1c832 ___CFXNotificationPost_block_invoke + 50
       	22  CoreFoundation                      0x00007fff859d95e2 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1922
       	23  CoreFoundation                      0x00007fff859d8835 _CFXNotificationPost + 693
       	24  Foundation                          0x00007fff94c0a17a -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
       	25  Foundation                          0x00007fff94ccd9e7 _NSPortDeathNotify + 76
       	26  CoreFoundation                      0x00007fff85a6e465 ____CFMachPortChecker_block_invoke + 69
       	27  libdispatch.dylib                   0x00007fff9230c93d _dispatch_call_block_and_release + 12
       	28  libdispatch.dylib                   0x00007fff9230140b _dispatch_client_callout + 8
       	29  libdispatch.dylib                   0x00007fff92314c1c _dispatch_main_queue_callback_4CF + 1685
       	30  CoreFoundation                      0x00007fff85a469e9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
       	31  CoreFoundation                      0x00007fff85a058dd __CFRunLoopRun + 1949
       	32  CoreFoundation                      0x00007fff85a04ed8 CFRunLoopRunSpecific + 296
       	33  HIToolbox                           0x00007fff8f346935 RunCurrentEventLoopInMode + 235
       	34  HIToolbox                           0x00007fff8f34676f ReceiveNextEventCommon + 432
       	35  HIToolbox                           0x00007fff8f3465af _BlockUntilNextEventMatchingListInModeWithFilter + 71
       	36  AppKit                              0x00007fff8225adf6 _DPSNextEvent + 1067
       	37  AppKit                              0x00007fff8225a226 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
       	38  AppKit                              0x00007fff8224ed80 -[NSApplication run] + 682
       	39  macfusionAgent                      0x0000000100000efa main + 138
       	40  macfusionAgent                      0x0000000100000e64 start + 52
)
2016-09-06 22:18:29.934 macfusionAgent[19921:669261] *** Terminating app due to uncaught exception 'NSInvalidReceivePortException', reason: 'connection is invalid'
*** First throw call stack:
(
       	0   CoreFoundation                      0x00007fff85a914f2 __exceptionPreprocess + 178
       	1   libobjc.A.dylib                     0x00007fff8cd5873c objc_exception_throw + 48
       	2   CoreFoundation                      0x00007fff85af84bd +[NSException raise:format:] + 205
       	3   Foundation                          0x00007fff94ca0680 -[NSConnection sendInvocation:internal:] + 239
       	4   Foundation                          0x00007fff94c9ff04 -[NSDistantObject methodSignatureForSelector:] + 538
       	5   CoreFoundation                      0x00007fff85a012b8 ___forwarding___ + 312
       	6   CoreFoundation                      0x00007fff85a010f8 _CF_forwarding_prep_0 + 120
       	7   Foundation                          0x00007fff94d52f82 -[NSDistantObject isEqual:] + 68
       	8   CoreFoundation                      0x00007fff85a16fbc -[NSMutableArray removeObject:] + 156
       	9   MFCore                              0x000000010001a99f -[MFCommunicationServer handleConnectionDidDie:] + 259
       	10  CoreFoundation                      0x00007fff85a1cbbc __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
       	11  CoreFoundation                      0x00007fff85a1cb4f ___CFXRegistrationPost_block_invoke + 63
       	12  CoreFoundation                      0x00007fff85a1cac7 _CFXRegistrationPost + 407
       	13  CoreFoundation                      0x00007fff85a1c832 ___CFXNotificationPost_block_invoke + 50
       	14  CoreFoundation                      0x00007fff859d95e2 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1922
       	15  CoreFoundation                      0x00007fff859d8835 _CFXNotificationPost + 693
       	16  Foundation                          0x00007fff94c0a17a -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
       	17  Foundation                          0x00007fff94d3e47f -[NSConnection invalidate] + 879
       	18  CoreFoundation                      0x00007fff85a1cbbc __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
       	19  CoreFoundation                      0x00007fff85a1cb4f ___CFXRegistrationPost_block_invoke + 63
       	20  CoreFoundation                      0x00007fff85a1cac7 _CFXRegistrationPost + 407
       	21  CoreFoundation                      0x00007fff85a1c832 ___CFXNotificationPost_block_invoke + 50
       	22  CoreFoundation                      0x00007fff859d95e2 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1922
       	23  CoreFoundation                      0x00007fff859d8835 _CFXNotificationPost + 693
       	24  Foundation                          0x00007fff94c0a17a -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
       	25  Foundation                          0x00007fff94ccd9e7 _NSPortDeathNotify + 76
       	26  CoreFoundation                      0x00007fff85a6e465 ____CFMachPortChecker_block_invoke + 69
       	27  libdispatch.dylib                   0x00007fff9230c93d _dispatch_call_block_and_release + 12
       	28  libdispatch.dylib                   0x00007fff9230140b _dispatch_client_callout + 8
       	29  libdispatch.dylib                   0x00007fff92314c1c _dispatch_main_queue_callback_4CF + 1685
       	30  CoreFoundation                      0x00007fff85a469e9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
       	31  CoreFoundation                      0x00007fff85a058dd __CFRunLoopRun + 1949
       	32  CoreFoundation                      0x00007fff85a04ed8 CFRunLoopRunSpecific + 296
       	33  HIToolbox                           0x00007fff8f346935 RunCurrentEventLoopInMode + 235
       	34  HIToolbox                           0x00007fff8f34676f ReceiveNextEventCommon + 432
       	35  HIToolbox                           0x00007fff8f3465af _BlockUntilNextEventMatchingListInModeWithFilter + 71
       	36  AppKit                              0x00007fff8225adf6 _DPSNextEvent + 1067
       	37  AppKit                              0x00007fff8225a226 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
       	38  AppKit                              0x00007fff8224ed80 -[NSApplication run] + 682
       	39  macfusionAgent                      0x0000000100000efa main + 138
       	40  macfusionAgent                      0x0000000100000e64 start + 52
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6
```

This is with a recent install of El Capitan and the 2.1-dev release.

If there are any details you'd like just ask. Sorry if this is unhelpful as I'm not really sure what you would have tried already. I'm in the process of installing Xcode and I might try to mess around with it to see what I can learn.

**Comment by ElDeveloper** [comment]
After @tessus' fix in #30, mfctl should be working. Please reopen if that's not the case though.

**Comment by nickcoutsos** [comment]
I've just built from master and while it appears that the given change takes care of linking the MFCore library I still get the error listed above when attempting to use mfctl.

**Comment by tessus** [comment]
@nickcoutsos can you please tell me how you run it.

on my machine:

```
cd Macfusion.app/Contents/Resources
./mfctl

No arguments given. Exiting!
```

**Comment by nickcoutsos** [comment]
mfctl itself seems to make it through alright but as I mentioned earlier the agent crashes everytime.

```
$ cd /Applications/Macfusion.app/Contents/Resources/
$ ./macfusionAgent.app/Contents/MacOS/macfusionAgent &
[1] 7404
$ ./mfctl
No arguments given. Exiting!

2016-10-24 14:10:39.891 macfusionAgent[7404:617702] An uncaught exception was raised
2016-10-24 14:10:39.892 macfusionAgent[7404:617702] connection is invalid
2016-10-24 14:10:39.892 macfusionAgent[7404:617702] (
	0   CoreFoundation                      0x00007fff915d24f2 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff94da673c objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff916394bd +[NSException raise:format:] + 205
	3   Foundation                          0x00007fff9ea27680 -[NSConnection sendInvocation:internal:] + 239
	4   Foundation                          0x00007fff9ea26f04 -[NSDistantObject methodSignatureForSelector:] + 538
	5   CoreFoundation                      0x00007fff915422b8 ___forwarding___ + 312
	6   CoreFoundation                      0x00007fff915420f8 _CF_forwarding_prep_0 + 120
	7   Foundation                          0x00007fff9ead9f82 -[NSDistantObject isEqual:] + 68
	8   CoreFoundation                      0x00007fff91557fbc -[NSMutableArray removeObject:] + 156
	9   MFCore                              0x0000000103fe550e -[MFCommunicationServer handleConnectionDidDie:] + 425
	10  CoreFoundation                      0x00007fff9155dbbc __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	11  CoreFoundation                      0x00007fff9155db4f ___CFXRegistrationPost_block_invoke + 63
	12  CoreFoundation                      0x00007fff9155dac7 _CFXRegistrationPost + 407
	13  CoreFoundation                      0x00007fff9155d832 ___CFXNotificationPost_block_invoke + 50
	14  CoreFoundation                      0x00007fff9151a5e2 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1922
	15  CoreFoundation                      0x00007fff91519835 _CFXNotificationPost + 693
	16  Foundation                          0x00007fff9e99117a -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
	17  Foundation                          0x00007fff9eac547f -[NSConnection invalidate] + 879
	18  CoreFoundation                      0x00007fff9155dbbc __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	19  CoreFoundation                      0x00007fff9155db4f ___CFXRegistrationPost_block_invoke + 63
	20  CoreFoundation                      0x00007fff9155dac7 _CFXRegistrationPost + 407
	21  CoreFoundation                      0x00007fff9155d832 ___CFXNotificationPost_block_invoke + 50
	22  CoreFoundation                      0x00007fff9151a5e2 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1922
	23  CoreFoundation                      0x00007fff91519835 _CFXNotificationPost + 693
	24  Foundation                          0x00007fff9e99117a -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
	25  Foundation                          0x00007fff9ea549e7 _NSPortDeathNotify + 76
	26  CoreFoundation                      0x00007fff915af465 ____CFMachPortChecker_block_invoke + 69
	27  libdispatch.dylib                   0x00007fff938b493d _dispatch_call_block_and_release + 12
	28  libdispatch.dylib                   0x00007fff938a940b _dispatch_client_callout + 8
	29  libdispatch.dylib                   0x00007fff938bcc1c _dispatch_main_queue_callback_4CF + 1685
	30  CoreFoundation                      0x00007fff915879e9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	31  CoreFoundation                      0x00007fff915468dd __CFRunLoopRun + 1949
	32  CoreFoundation                      0x00007fff91545ed8 CFRunLoopRunSpecific + 296
	33  HIToolbox                           0x00007fff8ca33935 RunCurrentEventLoopInMode + 235
	34  HIToolbox                           0x00007fff8ca3376f ReceiveNextEventCommon + 432
	35  HIToolbox                           0x00007fff8ca335af _BlockUntilNextEventMatchingListInModeWithFilter + 71
	36  AppKit                              0x00007fff98b60df6 _DPSNextEvent + 1067
	37  AppKit                              0x00007fff98b60226 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
	38  AppKit                              0x00007fff98b54d80 -[NSApplication run] + 682
	39  macfusionAgent                      0x0000000103fc0577 main + 122
	40  libdyld.dylib                       0x00007fff93bf85ad start + 1
)
2016-10-24 14:10:39.892 macfusionAgent[7404:617702] *** Terminating app due to uncaught exception 'NSInvalidReceivePortException', reason: 'connection is invalid'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff915d24f2 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff94da673c objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff916394bd +[NSException raise:format:] + 205
	3   Foundation                          0x00007fff9ea27680 -[NSConnection sendInvocation:internal:] + 239
	4   Foundation                          0x00007fff9ea26f04 -[NSDistantObject methodSignatureForSelector:] + 538
	5   CoreFoundation                      0x00007fff915422b8 ___forwarding___ + 312
	6   CoreFoundation                      0x00007fff915420f8 _CF_forwarding_prep_0 + 120
	7   Foundation                          0x00007fff9ead9f82 -[NSDistantObject isEqual:] + 68
	8   CoreFoundation                      0x00007fff91557fbc -[NSMutableArray removeObject:] + 156
	9   MFCore                              0x0000000103fe550e -[MFCommunicationServer handleConnectionDidDie:] + 425
	10  CoreFoundation                      0x00007fff9155dbbc __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	11  CoreFoundation                      0x00007fff9155db4f ___CFXRegistrationPost_block_invoke + 63
	12  CoreFoundation                      0x00007fff9155dac7 _CFXRegistrationPost + 407
	13  CoreFoundation                      0x00007fff9155d832 ___CFXNotificationPost_block_invoke + 50
	14  CoreFoundation                      0x00007fff9151a5e2 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1922
	15  CoreFoundation                      0x00007fff91519835 _CFXNotificationPost + 693
	16  Foundation                          0x00007fff9e99117a -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
	17  Foundation                          0x00007fff9eac547f -[NSConnection invalidate] + 879
	18  CoreFoundation                      0x00007fff9155dbbc __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	19  CoreFoundation                      0x00007fff9155db4f ___CFXRegistrationPost_block_invoke + 63
	20  CoreFoundation                      0x00007fff9155dac7 _CFXRegistrationPost + 407
	21  CoreFoundation                      0x00007fff9155d832 ___CFXNotificationPost_block_invoke + 50
	22  CoreFoundation                      0x00007fff9151a5e2 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1922
	23  CoreFoundation                      0x00007fff91519835 _CFXNotificationPost + 693
	24  Foundation                          0x00007fff9e99117a -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
	25  Foundation                          0x00007fff9ea549e7 _NSPortDeathNotify + 76
	26  CoreFoundation                      0x00007fff915af465 ____CFMachPortChecker_block_invoke + 69
	27  libdispatch.dylib                   0x00007fff938b493d _dispatch_call_block_and_release + 12
	28  libdispatch.dylib                   0x00007fff938a940b _dispatch_client_callout + 8
	29  libdispatch.dylib                   0x00007fff938bcc1c _dispatch_main_queue_callback_4CF + 1685
	30  CoreFoundation                      0x00007fff915879e9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	31  CoreFoundation                      0x00007fff915468dd __CFRunLoopRun + 1949
	32  CoreFoundation                      0x00007fff91545ed8 CFRunLoopRunSpecific + 296
	33  HIToolbox                           0x00007fff8ca33935 RunCurrentEventLoopInMode + 235
	34  HIToolbox                           0x00007fff8ca3376f ReceiveNextEventCommon + 432
	35  HIToolbox                           0x00007fff8ca335af _BlockUntilNextEventMatchingListInModeWithFilter + 71
	36  AppKit                              0x00007fff98b60df6 _DPSNextEvent + 1067
	37  AppKit                              0x00007fff98b60226 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
	38  AppKit                              0x00007fff98b54d80 -[NSApplication run] + 682
	39  macfusionAgent                      0x0000000103fc0577 main + 122
	40  libdyld.dylib                       0x00007fff93bf85ad start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by tessus** [comment]
Where's this `libc++abi.dylib` coming from? In none of my executables is this library linked.

**Comment by nickcoutsos** [comment]
Not sure. I'm already in over my head, but just to be sure it's not something I did during compiling I tried again with the "Sierra Pre-release 3" and got the same result. The only change I made was using `install_name_tool` like above to add MFCore.

**Comment by tessus** [comment]
The `Sierra Pre-release 3` does not have the fix. But, if you used `install_name_tool`, it should work with the Pre-release 3 too.

I wouldn't know why running mfctl would cause the agent to crash. maybe you have an old agent running.
What target did you compile?

The strange thing is that the agent does no crash on my machine. So why does it crash on yours?
The thing is, if I can't reproduce the problem, I can't fix it.

**Comment by nickcoutsos** [comment]
I used the makefile, so I guess "All", except when I used one of the uploaded releases to show that it's not a result of my compiler.

**Comment by tessus** [comment]
I still can't reproduce this issue. Maybe @ElDeveloper has more luck.

**Comment by ElDeveloper** [comment]
@nickcoutsos I tried the exact same commands as you above but didn't get any error at all:

```
yoshikivazquezbaeza:Resources$ ./macfusionAgent.app/Contents/MacOS/macfusionAgent &
[1] 24655
yoshikivazquezbaeza:Resources$ ./mfctl 
No arguments given. Exiting!
```

Just to confirm, you are compiling the project in your machine (from the tip of master)? Then from the built binaries you try to run those steps above?

Also, just in case the agent is causing some sort of trouble, try running:

```
killall macfusionAgent
```
